// TMC2130 stepper driver init

#if AXIS1_DRIVER_MODEL == TMC2130
  #undef AXIS1_DRIVER_MODEL
  #define AXIS1_DRIVER_MODEL TMC_SPI
#elif AXIS1_DRIVER_MODEL == TMC2130_LOWPWR
  #undef AXIS1_DRIVER_MODEL
  #define AXIS1_DRIVER_MODEL TMC_SPI
  #define AXIS1_TMC_IHOLD 1000 // 40% of Vref setting on trim-pot
  #define AXIS1_TMC_IRUN 1250  // 50%
  #define AXIS1_TMC_IGOTO 2500 // 100%
#elif AXIS1_DRIVER_MODEL == TMC2130_QUIET
  #undef AXIS1_DRIVER_MODEL
  #define AXIS1_DRIVER_MODEL TMC_SPI
  #define AXIS1_TMC_MODE STEALTHCHOP
#elif AXIS1_DRIVER_MODEL == TMC2130_QUIET_LOWPWR
  #undef AXIS1_DRIVER_MODEL
  #define AXIS1_DRIVER_MODEL TMC_SPI
  #define AXIS1_TMC_MODE STEALTHCHOP
  #define AXIS1_TMC_IHOLD 1000
  #define AXIS1_TMC_IRUN 1250
  #define AXIS1_TMC_IGOTO 2500
#elif AXIS1_DRIVER_MODEL == TMC2130_VQUIET
  #undef AXIS1_DRIVER_MODEL
  #define AXIS1_DRIVER_MODEL TMC_SPI
  #define AXIS1_TMC_MODE STEALTHCHOP
  #define AXIS1_TMC_MODE_GOTO STEALTHCHOP
#elif AXIS1_DRIVER_MODEL == TMC2130_VQUIET_LOWPWR
  #undef AXIS1_DRIVER_MODEL
  #define AXIS1_DRIVER_MODEL TMC_SPI
  #define AXIS1_TMC_MODE STEALTHCHOP
  #define AXIS1_TMC_MODE_GOTO STEALTHCHOP
  #define AXIS1_TMC_IHOLD 1000
  #define AXIS1_TMC_IRUN 1250
  #define AXIS1_TMC_IGOTO 2500
#endif

#if AXIS2_DRIVER_MODEL == TMC2130
  #undef AXIS2_DRIVER_MODEL
  #define AXIS2_DRIVER_MODEL TMC_SPI
#elif AXIS2_DRIVER_MODEL == TMC2130_LOWPWR
  #undef AXIS2_DRIVER_MODEL
  #define AXIS2_DRIVER_MODEL TMC_SPI
  #define AXIS2_TMC_IHOLD 1000
  #define AXIS2_TMC_IRUN 1250
  #define AXIS2_TMC_IGOTO 2500
#elif AXIS2_DRIVER_MODEL == TMC2130_QUIET
  #undef AXIS2_DRIVER_MODEL
  #define AXIS2_DRIVER_MODEL TMC_SPI
  #define AXIS2_TMC_MODE STEALTHCHOP
#elif AXIS2_DRIVER_MODEL == TMC2130_QUIET_LOWPWR
  #undef AXIS2_DRIVER_MODEL
  #define AXIS2_DRIVER_MODEL TMC_SPI
  #define AXIS2_TMC_MODE STEALTHCHOP
  #define AXIS2_TMC_IHOLD 1000
  #define AXIS2_TMC_IRUN 1250
  #define AXIS2_TMC_IGOTO 2500
#elif AXIS2_DRIVER_MODEL == TMC2130_VQUIET
  #undef AXIS2_DRIVER_MODEL
  #define AXIS2_DRIVER_MODEL TMC_SPI
  #define AXIS2_TMC_MODE STEALTHCHOP
  #define AXIS2_TMC_MODE_GOTO STEALTHCHOP
#elif AXIS2_DRIVER_MODEL == TMC2130_VQUIET_LOWPWR
  #undef AXIS2_DRIVER_MODEL
  #define AXIS2_DRIVER_MODEL TMC_SPI
  #define AXIS2_TMC_MODE STEALTHCHOP
  #define AXIS2_TMC_MODE_GOTO STEALTHCHOP
  #define AXIS2_TMC_IHOLD 1000
  #define AXIS2_TMC_IRUN 1250
  #define AXIS2_TMC_IGOTO 2500
#endif
