// TMC2209 stepper driver init

#if AXIS1_DRIVER_MODEL == TMC2209_QUIET
  #undef AXIS1_DRIVER_MODEL
  #define AXIS1_DRIVER_MODEL TMC2209
  #define AXIS1_DRIVER_DECAY_MODE STEALTHCHOP
#elif AXIS1_DRIVER_MODEL == TMC2209_VQUIET
  #undef AXIS1_DRIVER_MODEL
  #define AXIS1_DRIVER_MODEL TMC2209
  #define AXIS1_DRIVER_DECAY_MODE STEALTHCHOP
  #define AXIS1_DRIVER_DECAY_MODE_GOTO STEALTHCHOP
#endif

#if AXIS2_DRIVER_MODEL == TMC2209_QUIET
  #undef AXIS2_DRIVER_MODEL
  #define AXIS2_DRIVER_MODEL TMC2209
  #define AXIS2_DRIVER_DECAY_MODE STEALTHCHOP
#elif AXIS2_DRIVER_MODEL == TMC2209_VQUIET
  #undef AXIS2_DRIVER_MODEL
  #define AXIS2_DRIVER_MODEL TMC2209
  #define AXIS2_DRIVER_DECAY_MODE STEALTHCHOP
  #define AXIS2_DRIVER_DECAY_MODE_GOTO STEALTHCHOP
#endif

#if AXIS1_DRIVER_MODEL == TMC2209
  #define AXIS1_DRIVER_DISABLE_M2
  #ifdef AXIS1_DRIVER_DECAY_MODE
    #if AXIS1_DRIVER_DECAY_MODE == STEALTHCHOP
      #undef AXIS1_DRIVER_DECAY_MODE
      #define AXIS1_DRIVER_DECAY_MODE LOW
    #endif
    #if AXIS1_DRIVER_DECAY_MODE == SPREADCYCLE
      #undef AXIS1_DRIVER_DECAY_MODE
      #define AXIS1_DRIVER_DECAY_MODE HIGH
    #endif
  #else
    #define AXIS1_DRIVER_DECAY_MODE HIGH
  #endif
  #ifdef AXIS1_DRIVER_DECAY_MODE_GOTO
    #if AXIS1_DRIVER_DECAY_MODE_GOTO == STEALTHCHOP
      #undef AXIS1_DRIVER_DECAY_MODE_GOTO
      #define AXIS1_DRIVER_DECAY_MODE_GOTO LOW
    #endif
    #if AXIS1_DRIVER_DECAY_MODE_GOTO == SPREADCYCLE
      #undef AXIS1_DRIVER_DECAY_MODE_GOTO
      #define AXIS1_DRIVER_DECAY_MODE_GOTO HIGH
    #endif
  #else
    #define AXIS1_DRIVER_DECAY_MODE_GOTO HIGH
  #endif
#endif

#if AXIS2_DRIVER_MODEL == TMC2209
  #define AXIS2_DRIVER_DISABLE_M2
  #ifdef AXIS2_DRIVER_DECAY_MODE
    #if AXIS2_DRIVER_DECAY_MODE == STEALTHCHOP
      #undef AXIS2_DRIVER_DECAY_MODE
      #define AXIS2_DRIVER_DECAY_MODE LOW
    #endif
    #if AXIS2_DRIVER_DECAY_MODE == SPREADCYCLE
      #undef AXIS2_DRIVER_DECAY_MODE
      #define AXIS2_DRIVER_DECAY_MODE HIGH
    #endif
  #else
    #define AXIS2_DRIVER_DECAY_MODE HIGH
  #endif
  #ifdef AXIS2_DRIVER_DECAY_MODE_GOTO
    #if AXIS2_DRIVER_DECAY_MODE_GOTO == STEALTHCHOP
      #undef AXIS2_DRIVER_DECAY_MODE_GOTO
      #define AXIS2_DRIVER_DECAY_MODE_GOTO LOW
    #endif
    #if AXIS2_DRIVER_DECAY_MODE_GOTO == SPREADCYCLE
      #undef AXIS2_DRIVER_DECAY_MODE_GOTO
      #define AXIS2_DRIVER_DECAY_MODE_GOTO HIGH
    #endif
  #else
    #define AXIS2_DRIVER_DECAY_MODE_GOTO HIGH
  #endif
#endif
