// TMC2100 stepper driver init

#if AXIS1_DRIVER_MODEL == TMC2100 || AXIS2_DRIVER_MODEL == TMC2100
  #undef MODE_SWITCH_BEFORE_SLEW
  #define MODE_SWITCH_BEFORE_SLEW ON
  #undef MODE_SWITCH_SLEEP
  #define MODE_SWITCH_SLEEP ON
#endif
