// SERVO driver init

#if AXIS1_DRIVER_MODEL == GENERIC2
  #undef AXIS1_DRIVER_MODEL
  #define AXIS1_DRIVER_MODEL GENERIC
  #undef AXIS1_DRIVER_ENABLE
  #define AXIS1_DRIVER_ENABLE HIGH
#endif
#if AXIS2_DRIVER_MODEL == GENERIC2
  #undef AXIS2_DRIVER_MODEL
  #define AXIS2_DRIVER_MODEL GENERIC
  #undef AXIS2_DRIVER_ENABLE
  #define AXIS2_DRIVER_ENABLE HIGH
#endif
