// SERVO driver init

#if AXIS1_DRIVER_MODEL == GENERIC4
  #undef AXIS1_DRIVER_MODEL
  #define AXIS1_DRIVER_MODEL GENERIC2
  #define a1STEP a1STEP_L
  #define a1CLEAR a1STEP_H
#endif
#if AXIS2_DRIVER_MODEL == GENERIC4
  #undef AXIS2_DRIVER_MODEL
  #define AXIS2_DRIVER_MODEL GENERIC2
  #define a2STEP a2STEP_L
  #define a2CLEAR a2STEP_H
#endif
#if AXIS1_DRIVER_MODEL == GENERIC3
  #undef AXIS1_DRIVER_MODEL
  #define AXIS1_DRIVER_MODEL GENERIC
  #define a1STEP a1STEP_L
  #define a1CLEAR a1STEP_H
#endif
#if AXIS2_DRIVER_MODEL == GENERIC3
  #undef AXIS2_DRIVER_MODEL
  #define AXIS2_DRIVER_MODEL GENERIC
  #define a2STEP a2STEP_L
  #define a2CLEAR a2STEP_H
#endif
#if AXIS1_DRIVER_MODEL == GENERIC2
  #undef AXIS1_DRIVER_MODEL
  #define AXIS1_DRIVER_MODEL GENERIC
  #undef AXIS1_DRIVER_ENABLE
  #define AXIS1_DRIVER_ENABLE HIGH
#endif
#if AXIS2_DRIVER_MODEL == GENERIC2
  #undef AXIS2_DRIVER_MODEL
  #define AXIS2_DRIVER_MODEL GENERIC
  #undef AXIS2_DRIVER_ENABLE
  #define AXIS2_DRIVER_ENABLE HIGH
#endif
